### ISSUE TITLE
`addSpacerAlignments` maximum `n_mismatches` query

### ISSUE THREAD

**Issue by MatthewPace98** [crisprVerse/crisprDesign#16]
Our team has detected some off-target editing _in vitro_  in regions with 4 or 5 mismatches when aligned to the gRNA, and we would like to design guides with this in mind. I understand that increasing the number of allowed mismatches would exponentially increase the computational demand, but I think it would be useful to attempt `addSpacerAlignments` with `n_mismatches`> 3. Could this be implemented, please?

**Comment by Jfortin1** [comment]
This is possible using `bwa` instead of `bowtie` as the `aligner`
