### ISSUE TITLE
DNA and RNA bulge off target DSB

### ISSUE THREAD

**Issue by frvcw** [crisprVerse/crisprDesign#23]
Hi 

I want to consider the off target risk of DNA and gRNA bulges in the design of my protospacers. Is there a system in CrisprVerse that allows me to do it with my custom pakage genomes or should I rely on other programs e.g. Cas OFF finder? 

Thank for your work

**Comment by Jfortin1** [comment]
Hi @frvcw,

Unfortunately, our current aligners don't support DNA/RNA bulges
