### ISSUE TITLE
unpublished genome not recognised in biomaRt

### ISSUE THREAD

**Issue by liechi** [crisprVerse/crisprDesign#38]
Hi, I am trying to use crisprDesign for my gRNA search in a genome not yet published in open database.

I built a BSgenome and created a txdb object for this genome. When I function 'addSpacerAlignments', I got an error message saying the organism is not recognised in biomaRt.

I am wondering whether there is a way to use crisprDesign for unpublished genome? and if it is possible, would you please show a small demo?

Thanks a lot.

**Comment by Jfortin1** [comment]
Hi @liechi, could you copy the exact code that you've been using?

**Comment by liechi** [comment]
Hi, @Jfortin1 Thank you very much for taking care of this issue. 

I just found that the 'organism = ' is not an essential setting for the programe to run and if I do not set this, the program runs smoothly with out the 'organism is not recognised in biomaRt' error message. So, it is OK to close this issue.

Thanks a lot for this nice program.
